apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/configmap.yaml
  - base/mcp-api-gateway
  - base/auth-service
  - base/mcp-control-plane
  - base/model-service
  - base/ai-assistant
  - base/recommendation-engine
  - base/product-service
  - base/user-service
  - base/payment-service
  - base/frontend
  - base/redis
  # postgresql removed — using AWS RDS instead
