apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: mcp-platform
data:
  POSTGRES_HOST: "quantamvector.crqai6ems4a2.ap-northeast-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_SSLMODE: "require"
